keys:
    - &admin_tom age1hm8pnurl30mmfds8fj24k842znufaxlgxds9489tcz3h25un23jqm8qzf4
    - &server_gcp age1j4qeyjqc5xhuxa7pal2slc6j0smv5slrd484j55jqjppmxavcu5saf6wgy

creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
      - age:
        - *admin_tom
        - *server_gcp

