keys:
    - &admin_tom age1hm8pnurl30mmfds8fj24k842znufaxlgxds9489tcz3h25un23jqm8qzf4
    - &server_gcp_3 age124zgmnx48l7g04xpfcz7hefk0q7ec3s5prpqkn3ks96jppxacphsqh22eg

creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
      - age:
        - *admin_tom
        - *server_gcp_3
